AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Image Service API - LocalStack SAM Template
Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    Handler: app.lambda_handler
    Environment:
      Variables:
        TABLE_NAME:
          Ref: ImageTable
        BUCKET_NAME:
          Ref: ImageBucket
Resources:
  ImageApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
    Metadata:
      SamResourceId: ImageApi
  ImageUploadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-f2330092/cdcc6a09bd1e46027e68d53df8f98a7e
      Events:
        UploadApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ImageApi
            Path: /images
            Method: POST
    Metadata:
      SamResourceId: ImageUploadFunction
  ImageListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-f2330092/cdcc6a09bd1e46027e68d53df8f98a7e
      Events:
        ListApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ImageApi
            Path: /images
            Method: GET
    Metadata:
      SamResourceId: ImageListFunction
  ImageGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-f2330092/cdcc6a09bd1e46027e68d53df8f98a7e
      Events:
        GetApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ImageApi
            Path: /images/{imageId}
            Method: GET
    Metadata:
      SamResourceId: ImageGetFunction
  ImageDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-f2330092/cdcc6a09bd1e46027e68d53df8f98a7e
      Events:
        DeleteApi:
          Type: Api
          Properties:
            RestApiId:
              Ref: ImageApi
            Path: /images/{imageId}
            Method: DELETE
    Metadata:
      SamResourceId: ImageDeleteFunction
  ImageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: image-metadata
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
    Metadata:
      SamResourceId: ImageTable
  ImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: image-service-bucket
    Metadata:
      SamResourceId: ImageBucket
Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint
    Value:
      Fn::Sub: http://${ImageApi}.execute-api.${AWS::Region}.amazonaws.com/dev
  ImageTableName:
    Value:
      Ref: ImageTable
  ImageBucketName:
    Value:
      Ref: ImageBucket
